In [2]:
import numpy as np

In [5]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
List=list((2, 3.2, 5.5, -6.4, -2.2, 2.4))

In [12]:
a=np.array(List)

In [13]:
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [14]:
a[1]

3.2

In [15]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [17]:
List1=list(([[2, 3.2, 5.5, -6.4, -2.2,2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]))

In [18]:
a1=np.array((List1))

In [19]:
a1

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [21]:
a1[:,3]

array([-6.4,  0.1, 21. ])

In [23]:
a1[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [24]:
a1[1:,2]

array([4. , 2.1])

In [48]:
arr=np.array((np.arange(4),np.arange(10,14)))

In [50]:
np.shape(arr)

(2, 4)

In [51]:
arr.size

8

In [52]:
arr.max()

13

In [53]:
arr.min()

0

In [54]:
arr1=arr.reshape(2,2,2)

In [55]:
arr1

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [56]:
arr1.T

array([[[ 0, 10],
        [ 2, 12]],

       [[ 1, 11],
        [ 3, 13]]])

In [57]:
arr1.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [62]:
arr2=np.array((np.arange(4),np.arange(10,14)),dtype=float)

In [63]:
arr2

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

In [64]:
arr3=np.arange(1,21)

In [65]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
A=np.arange(1,9).reshape(2,4)

In [69]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
B=np.array([1,2])

In [80]:
B=B.reshape(2,1)

In [82]:
A+B

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [83]:
import random

In [90]:
np.random.rand(8)

array([0.39505802, 0.88968971, 0.3127122 , 0.73427546, 0.18332503,
       0.28599176, 0.78135262, 0.98984144])

In [91]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])